# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c30946de9036dbe8d13d3b40b98ef707ccc204ef75aeff798f12796ac8ad187a0e5fbff4bdb968a8901591fa0f65fd2a04bcce0606bf96ec6f44581d027b80

test:
  secret_key_base: 55532cdf774a8a2782707d7d7156f0342ff3ac1400a81282fb40ef1955b275f6c64bc92ac646b99e3d9acf432ffc65a3abda5e4bfa9f309792fa6af0dea5c323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
